
RANGE = {
    'ALT': [2, 10000],
    'Albumin': [0.6, 6],
    'AST': [6, 20000],
    'Bicarbonate': [0, 60],
    'Total Bilirubin': [0.1, 60],
    'Creatinine': [0.1, 60],
    'DBP': [0, 375],
    'gcs-eyeopening': [1, 4],
    'gcs-motorresponse': [1, 6],
    'gcs-verbalresponse': [1, 5],
    'Glucose (ch)': [33, 2000],
    'Glucose (blood gas)': [33, 2000],
    'HR': [0, 350],
    'Hematocrit': [0, 75],
    'Hemoglobin (hematology)': [0, 25],
    'Hemoglobin (blood gas)': [0, 25],
    'Lactate': [0.4, 30],
    'MBP': [14, 330],
    'ph/bloodgas': [6.3, 8.4],
    'Phosphate': [0.5, 20],
    'Platelet Count': [0, 2000],
    'Potassium (ch)': [0, 12],
    'Potassium (whole blood)': [0, 12],
    'RR': [0, 300],
    'SBP': [0, 375],
    'temperature': [26, 45],
    'Troponin I': [0.01, 49.6],
    'Troponin T': [0.01, 20.85],
    'WBC': [0, 1000],
}
    
HEADER = [
    'HADM_ID',
    'ICUSTAY_ID', 
    'START_TIME', 
    'END_TIME',
    'SORETIME',
    'EVENTTIME',
    'DBP',
    'MBP',
    'SBP',
    'activity',
    'friction/shear',
    'mobility',
    'moisture',
    'nutrition',
    'sensory/perception',
    'gcs-eyeopening',
    'gcs-motorresponse',
    'gcs-verbalresponse',
    'HR',
    'SaO2',
    'SpO2',
    'RR',
    'temperature',
    'ph/bloodgas',
    'pO2/bloodgas',
    'pCO2/bloodgas',
    'Bicarbonate',
    'CalculatedBicarbonate',
    'Hemoglobin (hematology)',
    'Hemoglobin (blood gas)',
    'Hematocrit',
    'CalculatedHematocrit',
    '_WBCCount',
    'WBC',
    'Neutrophils',
    'Platelet Count',
    'INR(PT)',
    'Glucose (ch)',
    'Glucose (blood gas)',
    'Lactate',
    'Sodium (ch)',
    'Sodium (whole blood)',
    'Potassium (ch)',
    'Potassium (whole blood)',
    'Total Calcium',
    'Phosphate',
    '_Total Protein',
    'Albumin',
    'ALT',
    'AST',
    'Total Bilirubin',
    'Urea Nitrogen',
    'Creatinine',
    'Uric Acid',
    'C-Reactive Protein',
    'Troponin I',
    'Troponin T'
]

DTYPES = {
        'HADM_ID': str,
        'ICUSTAY_ID': str, 
        'START_TIME': str, 
        'END_TIME': str,
        'SORETIME': str,
        'EVENTTIME': str,
        'DBP': float,
        'MBP': float,
        'SBP': float,
        'activity': float,
        'friction/shear': float,
        'mobility': float,
        'moisture': float,
        'nutrition' :float,
        'sensory/perception': float,
        'gcs-eyeopening': float,
        'gcs-motorresponse': float,
        'gcs-verbalresponse': float,
        'HR': float,
        'SaO2': float,
        'SpO2': float,
        'RR': float,
        'temperature': float,
        'ph/bloodgas': float,
        'pO2/bloodgas': float,
        'pCO2/bloodgas': float,
        'Bicarbonate': float,
        'CalculatedBicarbonate': float,
        'Hemoglobin (hematology)': float,
        'Hemoglobin (blood gas)': float,
        'Hematocrit': float,
        'CalculatedHematocrit': float,
        '_WBCCount': float,
        'WBC': float,
        'Neutrophils': float,
        'Platelet Count': float,
        'INR(PT)': float,
        'Glucose (ch)': float,
        'Glucose (blood gas)': float,
        'Lactate': float,
        'Sodium (ch)': float,
        'Sodium (whole blood)': float,
        'Potassium (ch)': float,
        'Potassium (whole blood)': float,
        'Total Calcium': float,
        'Phosphate': float,
        '_Total Protein': float,
        'Albumin':float,
        'ALT': float,
        'AST': float,
        'Total Bilirubin': float,
        'Urea Nitrogen': float,
        'Creatinine': float,
        'Uric Acid': float,
        'C-Reactive Protein': float,
        'Troponin I': float,
        'Troponin T': float,
    }
